# Generated by Django 5.2.6 on 2025-09-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_category_article_authors_article_feature_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categorys',
            new_name='category',
        ),
    ]
