# Generated by Django 5.2.6 on 2025-09-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_alter_comment_id_alter_commentreaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction_type',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('love', 'Love'), ('surprised', 'Surprised')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('love', 'Love'), ('surprised', 'Surprised')], max_length=20),
        ),
    ]
